[cluster]
first_node ansible_host=192.168.199.248
second_node ansible_host=192.168.199.244
third_node ansible_host=192.168.199.17

[cluster:vars]
bastion_server=87.228.13.8
ansible_user=root
ansible_ssh_common_args='-o ProxyCommand="ssh -o StrictHostKeyChecking=accept-new -W %h:%p -q {{ ansible_user }}@{{ bastion_server }}"'

[bastion]
bastion_server ansible_host=87.228.13.8 ansible_connection=ssh ansible_user=root