[cluster]
first_node ansible_host=192.168.199.41
second_node ansible_host=192.168.199.42
third_node ansible_host=192.168.199.43

[cluster:vars]
bastion_server=87.228.8.13
ansible_user=root
ansible_ssh_common_args='-o ProxyCommand="ssh -o StrictHostKeyChecking=accept-new -W %h:%p -q {{ ansible_user }}@{{ bastion_server }}"'

[bastion]
bastion_server ansible_host=87.228.8.13 ansible_connection=ssh ansible_user=root