services:
  grafana:
    image: grafana/grafana-oss
    ports: ["3000:3000"]
    depends_on:
      - prometheus
    volumes:
      - type: bind
      - source: /usr/local/lib/grafana
      - target: /var/lib/grafana
    networks:
      - app-net

  nginx:
    image: nginx
    volumes:
      - type: volume
        source: data
        target: /etc/nginx
    networks:
      - app-net

  prometheus:
    image:
    volumes:
      - type: bind
      - source: /usr/local/lib/prometheus
      - target: /var/lib/prometheus
    networks:
      - app-net

volumes:
  data:

networks:
  app-net:
    external:
      name: nat