upstream front {
  server demo-nginx-1:8888;  # Container 1 (TCP)
  server demo-nginx-2:8888;  # Container 2 (TCP)
  server demo-nginx-3:8888;  # Container 3 (TCP)
}

server {
  listen 8888;
  location / {
    add_header Content-Type text/plain;
    proxy_pass http://front;
  }
}
