services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - prometheus
      - cadvisor

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana.yml:/etc/grafana/provisioning/datasources/grafana.yml
    ports:
      - "3000:3000"
    networks:
      - grafana
      - prometheus


  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    networks:
      - cadvisor

  lb:
    image: nginx
    volumes:
      - ./lb.conf:/etc/nginx/conf.d/lb.conf
    ports:
      - "8888:8888"
    depends_on:
      - nginx
    networks:
      - web

  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./custom.conf:/etc/nginx/conf.d/custom.conf
    deploy:
      mode: replicated
      replicas: 3
    networks:
      - web

networks:
  grafana:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "br@grafana"
  prometheus:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "br@prometheus"
  web:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "br@web"
  cadvisor:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "br@cadvisor"