---
- name: Prepare everything for running docker-compose
  gather_facts: false
  hosts: docker

  tasks:
    - name: Copy files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/root/"
        mode: '0644'
      with_items:
        - ./docker/custom.conf
        - ./docker/docker-compose.yml
        - ./docker/grafana.yml
        - ./docker/lb.conf
        - ./docker/prometheus.yml

    - name: Copy file for Docker's apt repository.
      ansible.builtin.copy:
        src: ./docker/docker.list
        dest: /etc/apt/sources.list.d/docker.list
        mode: '0644'

    - name: Update cache and install Docker
      ansible.builtin.apt:
        update_cache: true
        name: "{{ item }}"
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
        -
    - name: Copy file for Docker's daemon.json to enable metrics-addr
      ansible.builtin.copy:
        src: ./docker/daemon.json
        dest: /etc/docker/daemon.json
        mode: '0644'

    # Iptables block
    - name: Allow all 192.168.199.0/24 traffic
      ansible.builtin.iptables:
        in_interface: eth0
        chain: INPUT
        source: 192.168.199.0/24
        jump: ACCEPT
        action: insert

    - name: Allow 188.93.16.0/22 subnet
      ansible.builtin.iptables:
        in_interface: eth0
        chain: INPUT
        source: 188.93.16.0/22
        jump: ACCEPT
        action: insert

    - name: Allow related and established connections
      ansible.builtin.iptables:
        in_interface: eth0
        chain: INPUT
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT
        action: insert

    - name: Prohibit everything else
      ansible.builtin.iptables:
        in_interface: eth0
        chain: INPUT
        reject_with: icmp-host-prohibited
        action: append
