#cloud-config

timezone: Europe/Moscow

manage_etc_hosts: false

packages:
 - git
 - nmap

runcmd:
 - [ git, clone, https://opendev.org/openstack/devstack ]
 - [ bash, devstack/tools/create-stack-user.sh ]
 - [ mv, devstack, /opt/stack, ]
 - [ chown, -R, stack:stack, /opt/stack/devstack ]