[group]
grafana ansible_host=192.168.199.{{ REPLACE-ME-PRIVATE }}
nginx ansible_host=192.168.199.{{ REPLACE-ME-PRIVATE  }}
prometheus ansible_host=192.168.199.{{ REPLACE-ME-PRIVATE  }}
docker ansible_host={{ REPLACE-ME-PUBLIC }}

[group:vars]
bastion_server={{ REPLACE-ME-PUBLIC  }}
ansible_ssh_common_args='-o ProxyCommand="ssh -o StrictHostKeyChecking=accept-new -W %h:%p -q {{ ansible_user }}@{{ bastion_server }}"'

[bastion]
grafana_public ansible_host={{ REPLACE-ME-PUBLIC  }}

[all:vars]
ansible_user=root