[group]
grafana ansible_host=192.168.199.{{ REPLACE ME }}
nginx ansible_host=192.168.199.{{ REPLACE ME }}
prometheus ansible_host=192.168.199.{{ REPLACE ME }}

[group:vars]
bastion_server={{ REPLACE ME }}
ansible_ssh_common_args='-o ProxyCommand="ssh -o StrictHostKeyChecking=accept-new -W %h:%p -q {{ ansible_user }}@{{ bastion_server }}"'

[bastion]
grafana_public ansible_host={{ REPLACE ME }}

[all:vars]
ansible_user=root