[group]
grafana ansible_host=192.168.199.65
nginx ansible_host=192.168.199.87
prometheus ansible_host=192.168.199.123

[group:vars]
bastion_server=87.228.27.130
ansible_ssh_common_args='-o ProxyCommand="ssh -o StrictHostKeyChecking=accept-new -W %h:%p -q {{ ansible_user }}@{{ bastion_server }}"'

[bastion]
grafana_public ansible_host=87.228.27.130

[docker_group]
docker ansible_host=188.124.51.218

[all:vars]
ansible_user=root