---
- name: Deploy exporter on all machines
  ansible.builtin.import_playbook: ./playbooks/exporter.yml

- name: Deploy prometheus
  ansible.builtin.import_playbook: ./playbooks/prom.yml

- name: Deploy Grafana
  ansible.builtin.import_playbook: ./playbooks/grafana.yml

- name: Deploy nginx
  ansible.builtin.import_playbook: ./playbooks/nginx.yml

- name: Deploy docker
  ansible.builtin.import_playbook: ./playbooks/docker.yml
