[[local|localrc]]
# Controller node
HOST_IP=192.168.12.30
FIXED_RANGE=10.4.128.0/20
FLOATING_RANGE=192.168.12.0/25
LOGFILE=/opt/stack/logs/stack.sh.log
ADMIN_PASSWORD=passwordcontroller
DATABASE_PASSWORD=supersecret
RABBIT_PASSWORD=supersecret
SERVICE_PASSWORD=supersecret